### ISSUE TITLE
Reset function: functionality help

### ISSUE THREAD

**Issue by bigmoby** [maxill1/node-ialarm#14]
Hi @maxill1 ,
please could you give me a clarification about Reset function (https://github.com/maxill1/node-ialarm/blob/157b06f8eb99681819b269229779b0bd66d1b85d/src/meian-commands.js#L1136 ) ?
Specifically, I need to know if passing True performs a Reset of the alarm system or if it executes a Reboot. I would strongly like to avoid bricking my system :-) ...I wanna only Reboot the alarm!
Many thanks in advance,
Fabio

**Comment by maxill1** [comment]
Actually I don't know. I ported the median client from python to nodejs, but commented out all untested commands for safety reason.

Take a look here:
https://github.com/wildstray/meian-client/

**Comment by bigmoby** [comment]
Hi @maxill1 thanks a lot 👍 I'll try to ask @wildstray
