### ISSUE TITLE
installazione

### ISSUE THREAD

**Issue by wifi75** [maxill1/node-ialarm#5]
CIao Luca ho una centrale antifurto 365, come posso integrare il tuo codice in HA?
Ho anche un broker mqtt da sfruttare e Node red che uso per altri scopi, ma non ho capito come installare il tuo script.

potresti spiegarmi gentilmente?

**Comment by maxill1** [comment]
Ciao, questa è solo una libreria che viene richiamata dai vari plugin dedicati (quello per node-red, quello "autonomo" ialarm-mqtt, ed eventuali altri).

Personalmente utilizzo ialarm-mqtt tramite docker (compose) che espone automaticamente a home assistant le entità dell'antifurto, sensori e stato "triggered", "armed", etc. 
L'installazione in quel caso puoi farla in 2 modi: via docker o direttamente con nodejs via npx.

Le istruzioni le trovi qui:
https://github.com/maxill1/ialarm-mqtt/wiki/Installation

Alcuni mi chiedono di realizzare un addon per home assistant in modo da installarlo direttamente da UI, ma ho davvero poco tempo in questo periodo e poi non uso hassio ma direttamente home assistant su docker, quindi dovrei tirarmi su una macchina di test con hassio per fare un po di prove...al momento non riesco.
https://github.com/maxill1/ialarm-mqtt/issues/12
